In [1]:
import numpy

# load pima indians dataset
dataset = numpy.loadtxt('/home/datadrive/PythonDev/DeepLearningPython/TrainingData/Pimaindiandiabetes', delimiter=',')

# split into input (X) and output (Y) variables
X = dataset[:, 0:8]
Y = dataset[:, 8]

In [2]:
print(X[2])

[  1.     85.     66.     29.      0.     26.6     0.351  31.   ]


In [3]:
print(Y[2])

0.0


In [4]:
print(dataset[2])
print(X[2])
print(Y[2])

[   8.     183.      64.       0.       0.      23.3      0.672   32.       1.   ]
[   8.     183.      64.       0.       0.      23.3      0.672   32.   ]
1.0


In [1]:
import numpy
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline


seed = 7
numpy.random.seed(seed)

dataframe = read_csv('/home/datadrive/PythonDev/DeepLearningPython/MulticlassClassification/irisdata', header=None)
dataset = dataframe.values
# take first 4 items for each row convert to float
X = dataset[:, 0:4].astype(float)

# take last item - which is the classifier
Y = dataset[:, 4]

# lets encode the output variables
# We reshape from vector that contains values for each class value to; a matrix with a
# boolean for each class value. And whether or not a given instance has that class
# value or not. 'One hot encoding'
# for out classification of:
#   Iris-setosa
#   Iris-versicolor
#   Iris-virginica
#
# One-hot encoded to
#   Iris-setosa,     Iris-versicolor,     Iris-virginica
#        1,               0,                     0
#        0,               1,                     0
#        0,               0,                     1

# Encode string to integers using scikit-learn class LabelEncoder
# then convert vector of integers to a One-hot encoding using keras 'to_categorical()' function
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)

# convert the integers to dummy variables - one-hot encoded
dummy_y = np_utils.to_categorical(encoded_Y)

Using TensorFlow backend.


In [4]:
print(dummy_y)

[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1. 